### ISSUE TITLE
When deployed on a subpath, tag explorer errors out with a 404 and admin has a wrong URL

### ISSUE THREAD

**Issue by mmkay** [canonical/pyroscope-k8s-operator#36]
### Bug Description

If pyroscope is deployed on a subpath (behind ingress), "tag explorer" in pyroscope UI errors out with a 404. The "admin" link in the main navigation bar is also wrong. This view seems to ignore the base-url setting in pyroscope configuration. It might be an upstream bug.

![Image](https://github.com/user-attachments/assets/767fd184-78e7-4652-875a-f26584962c7d)

![Image](https://github.com/user-attachments/assets/b1d0c755-19ea-48b1-ab16-e68b31538f2c)

### To Reproduce

```
bundle: kubernetes
applications:
  minio:
    charm: minio
    channel: ckf-1.10/edge
    revision: 459
    base: ubuntu@20.04/stable
    resources:
      oci-image: 547
    scale: 1
    options:
      access-key: accesskey
      secret-key: secretkey
    constraints: arch=amd64
    storage:
      minio-data: kubernetes,1,10240M
    trust: true
  pyroscope-coordinator-k8s:
    charm: local:pyroscope-coordinator-k8s-15
    scale: 1
    constraints: arch=amd64
  pyroscope-worker-k8s:
    charm: pyroscope-worker-k8s
    channel: 2/edge
    revision: 1
    resources:
      pyroscope-image: 1
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  s3:
    charm: s3-integrator
    channel: latest/edge
    revision: 155
    base: ubuntu@22.04/stable
    scale: 1
    options:
      bucket: pyroscope
      endpoint: minio-0.minio-endpoints.test-pyroscope.svc.cluster.local:9000
    constraints: arch=amd64
    trust: true
  traefik-k8s:
    charm: traefik-k8s
    channel: latest/stable
    revision: 236
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 161
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - pyroscope-coordinator-k8s:pyroscope-cluster
  - pyroscope-worker-k8s:pyroscope-cluster
- - s3:s3-credentials
  - pyroscope-coordinator-k8s:s3
- - traefik-k8s:ingress
  - pyroscope-coordinator-k8s:ingress
```

### Environment

Found while implementing ingress / nginx.

### Relevant log output

```shell
.
```
